import FloatingHome from '../components/floating-home';
import './global.css';
import './globalicon.css';

export const metadata = {
  title: 'Welcome to payndit',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" href="/icons/logo.png" />
      </head>
      <body>
        {children}
        <FloatingHome />
      </body>
    </html>
  );
}
